from models import Note

A_flat = Note('A♭')
G_double_sharp = Note('G♯♯')
A = Note('A')
B_double_flat = Note('B♭♭')
A_sharp = Note('A♯')
B_flat = Note('B♭')
B = Note('B')
B_sharp = Note('B♯')
C_flat = Note('C♭')
C = Note('C')
C_sharp = Note('C♯')
D_double_flat = Note('D♭♭')
D_flat = Note('D♭')
D = Note('D')
D_sharp = Note('D♯')
E_flat = Note('E♭')
E = Note('E')
E_sharp = Note('E♯')
F_flat = Note('F♭')
F = Note('F')
F_sharp = Note('F♯')
G_flat = Note('G♭')
G = Note('G')
G_sharp = Note('G♯')